version: '2.2'

services:
  product:
    build: microservices/product-service
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  recommendation:
    build: microservices/recommendation-service
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: microservices/review-service
    mem_limit: 256m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 256m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mongodb:
    image: mongo:5.0.8
    mem_limit: 256m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60
