fullnameOverride: mysql

image:
  repository: registry.hub.docker.com/library
  name: mysql
  tag: 8.0.29
  pullPolicy: IfNotPresent
  args:
    - "--ignore-db-dir=lost+found"
ports:
  - containerPort: 3306

service:
  ports:
    - port: 3306

